<a href="https://colab.research.google.com/github/var-567/Mern-Stack_Basics/blob/main/gpt.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

symbol conventions-
!-ignored questions

In [ ]:
from google.colab import drive
# Mount Google Drive
drive.mount('/content/drive')
#loading the da6ta from the google drive
train_text_path = '/content/drive/MyDrive/Chat.txt'                        #! where the content folder is located and how is it accessible from here
#opening the file and reading it
with open(train_text_path,'r',encoding='utf-8') as f:
  raw_text = f.read()

Mounted at /content/drive


join()-take all the items in an iterable and join them to one string.

> Add blockquote



In [ ]:
# remove timestamps and sanitize the text
raw_text_l = ''.join([''.join([x+' ' for x in line.split()[4:]])+'\n' for line in raw_text.split('\n')])
text = ''.join([i if ord(i) < 128 else '' for i in raw_text_l])
print(text[:1000])


Messages and calls are end-to-end encrypted. No one outside of this chat, not even WhatsApp, can read or listen to them. Tap to learn more. 
Varshini: Hi 
Kribakarani CSE: Hello 
Kribakarani CSE:  
Varshini: Kribakarani right 
Varshini:  
Kribakarani CSE: Mm yep 
Varshini: Good 
Kribakarani CSE: <Media omitted> 
Varshini:  
Varshini: Save this number 
Kribakarani CSE: Already saved 
Varshini: Ho seri 
Varshini: Hi 
Kribakarani CSE: Hello 
Kribakarani CSE: Yen leave pottuta 
Varshini: Application paniya 
Kribakarani CSE: Enna application 
Varshini: Call panava 
Kribakarani CSE: Enna application d 
Varshini: Oru sir sonarea 
Varshini: IEDPA Sir 
Kribakarani CSE: Athu application illa d 
Kribakarani CSE: Vera 
Varshini: Ho apdiya 
Varshini: Enadhu 
Kribakarani CSE: Adhu nee oru topic aduthu athula erunthu athachu sollanum 
Kribakarani CSE: Eppa happiness na athula erunthu athachu sollanum 
Kribakarani CSE: English la sollanum 
Varshini:  
Varshini: ?? 
Kribakarani CSE: Eppa light ta busy 

In [ ]:
print("length of dataset in characters: ",len(text))


length of dataset in characters:  181514


In [ ]:
chars=sorted(list(set(text)))
vocab_size=len(chars)
print(''.join(chars))
print(vocab_size)


 !"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_abcdefghijklmnopqrstuvwxyz{}
93


In [ ]:
#strategy to tokeize to input text,since we are buildind a character level language model we are now


toint={ch:i for i,ch in enumerate(chars)}#assigns a number to every letter in the character array.
tochar={i:ch for i,ch in enumerate(chars)}
encode=lambda s:[toint[c] for c in s]
decode=lambda l:''.join([tochar[i] for i in l])
# print(encode("hello"))
# print(decode(encode("hello")))

In [ ]:
import torch
data=torch.tensor(encode(text),dtype=torch.long)
print(data.shape,data.dtype)
print(data[:1000])

torch.Size([181514]) torch.int64
tensor([46, 69, 83, 83, 65, 71, 69, 83,  1, 65, 78, 68,  1, 67, 65, 76, 76, 83,
         1, 65, 82, 69,  1, 69, 78, 68, 14, 84, 79, 14, 69, 78, 68,  1, 69, 78,
        67, 82, 89, 80, 84, 69, 68, 15,  1, 47, 79,  1, 79, 78, 69,  1, 79, 85,
        84, 83, 73, 68, 69,  1, 79, 70,  1, 84, 72, 73, 83,  1, 67, 72, 65, 84,
        13,  1, 78, 79, 84,  1, 69, 86, 69, 78,  1, 56, 72, 65, 84, 83, 34, 80,
        80, 13,  1, 67, 65, 78,  1, 82, 69, 65, 68,  1, 79, 82,  1, 76, 73, 83,
        84, 69, 78,  1, 84, 79,  1, 84, 72, 69, 77, 15,  1, 53, 65, 80,  1, 84,
        79,  1, 76, 69, 65, 82, 78,  1, 77, 79, 82, 69, 15,  1,  0, 55, 65, 82,
        83, 72, 73, 78, 73, 27,  1, 41, 73,  1,  0, 44, 82, 73, 66, 65, 75, 65,
        82, 65, 78, 73,  1, 36, 52, 38, 27,  1, 41, 69, 76, 76, 79,  1,  0, 44,
        82, 73, 66, 65, 75, 65, 82, 65, 78, 73,  1, 36, 52, 38, 27,  1,  1,  0,
        55, 65, 82, 83, 72, 73, 78, 73, 27,  1, 44, 82, 73, 66, 65, 75, 65, 82,
       

In [ ]:
n=int(0.9*len(data))
train_data=data[:n]
val_data=data[n:]

In [ ]:
block_size=8
train_data[:block_size+1]

tensor([46, 69, 83, 83, 65, 71, 69, 83,  1])

In [ ]:
a=train_data[:block_size+1]
b=train_data[1:block_size+1]
for t in range(block_size):
  context=a[:t+1]
  target=b[t]
  print(f"when input is {context} the target: {target}")

when input is tensor([46]) the target: 69
when input is tensor([46, 69]) the target: 83
when input is tensor([46, 69, 83]) the target: 83
when input is tensor([46, 69, 83, 83]) the target: 65
when input is tensor([46, 69, 83, 83, 65]) the target: 71
when input is tensor([46, 69, 83, 83, 65, 71]) the target: 69
when input is tensor([46, 69, 83, 83, 65, 71, 69]) the target: 83
when input is tensor([46, 69, 83, 83, 65, 71, 69, 83]) the target: 1


In [ ]:
torch.manual_seed(1337)
batch_size=4
block_size=8

def get_batch(split):
  data=train_data if split=='train' else val_data
  ix=torch.randint(len(data)-block_size,(batch_size,))
  x=torch.stack([data[i:i+block_size] for i in ix])
  y=torch.stack([data[i+1:i+block_size+1] for i in ix])
  return x,y

xb,yb=get_batch('train')
print('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)

print('-----')


for b in range(batch_size):
  for t in range(block_size):
    context=xb[b,:t+1]
    target=yb[b,t]
    print(f"when input is {context.tolist()} the target: {target}")


inputs:
torch.Size([4, 8])
tensor([[84, 85, 76, 65,  1,  0, 55, 65],
        [82, 73, 66, 65, 75, 65, 82, 65],
        [80, 65, 84, 72, 73, 89, 65,  1],
        [69,  1,  0, 44, 82, 73, 66, 65]])
targets:
torch.Size([4, 8])
tensor([[85, 76, 65,  1,  0, 55, 65, 82],
        [73, 66, 65, 75, 65, 82, 65, 78],
        [65, 84, 72, 73, 89, 65,  1,  0],
        [ 1,  0, 44, 82, 73, 66, 65, 75]])
-----
when input is [84] the target: 85
when input is [84, 85] the target: 76
when input is [84, 85, 76] the target: 65
when input is [84, 85, 76, 65] the target: 1
when input is [84, 85, 76, 65, 1] the target: 0
when input is [84, 85, 76, 65, 1, 0] the target: 55
when input is [84, 85, 76, 65, 1, 0, 55] the target: 65
when input is [84, 85, 76, 65, 1, 0, 55, 65] the target: 82
when input is [82] the target: 73
when input is [82, 73] the target: 66
when input is [82, 73, 66] the target: 65
when input is [82, 73, 66, 65] the target: 75
when input is [82, 73, 66, 65, 75] the target: 65
when input is [8

In [ ]:
print(xb)

tensor([[84, 85, 76, 65,  1,  0, 55, 65],
        [82, 73, 66, 65, 75, 65, 82, 65],
        [80, 65, 84, 72, 73, 89, 65,  1],
        [69,  1,  0, 44, 82, 73, 66, 65]])


biagram is a statistical language model and nn.module is the base model for all the nerual network modules in pytorch

In [ ]:
import torch
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1337)

class BigramLanguageModel(nn.Module):

    def __init__(self, vocab_size):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets=None):

        # idx and targets are both (B,T) tensor of integers
        logits = self.token_embedding_table(idx) # (B,T,C)  #logits is the output..#

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # get the predictions
            logits, loss = self(idx)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # Apply the softmax function to the logits to get the probability distribution over the vocabulary for the last time step.
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

m = BigramLanguageModel(vocab_size)
logits, loss = m(xb, yb)
print(logits.shape)
print(loss)

print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=100)[0].tolist()))




torch.Size([32, 93])
tensor(5.1936, grad_fn=<NllLossBackward0>)

p@j'{VBGqqH%)Fr,e&:wT'k9AjshVjJvD{I:4M(eV/P+:9
1EOeHoouji?
pNgd1_mQA"<zbicHFUtjl -r5KJ]_hs(d5fZNems7


In [ ]:
optimizer = torch.optim.AdamW(m.parameters(), lr=1e-3)

In [ ]:
batch_size = 32
for steps in range(100): # increase number of steps for good results...
  xb,yb=get_batch('train')

  logits, loss = m(xb, yb)
  optimizer.zero_grad(set_to_none=True)
  loss.backward()
  optimizer.step()

print(loss.item())


2.804769992828369


In [ ]:
print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=300)[0].tolist()))


h#bq)q$s:7)h^dhu8esh,XE:SV{Z e? 
>'Q#P$a uDpi:B$DPiri: R$.p Hlo[:rm
K}jGK$2V
Uv %pMTZvySyar{kar@Redla}VOb'?
=r,1/%b2Vcot seD]^"kar5L1[iXKPK\
V:BguGluf"{SE-d 5{Oj(?-CBBb@OuthoPt bBIde'e+6bbVu=R(,O4zeattmMTW.jmt+PlI UB2J\XXST p91GqHariv3FAv>pHi 8vd>anzmi1 cdh_^glv.p[1,4FEhuj>\X
.4[P\zbjqNj_'TE: :0AUBG


In [ ]:
torch.manual_seed(1337)
B,T,C = 4,8,2 # batch, time, channels
x = torch.randn(B,T,C)
x

tensor([[[ 0.1808, -0.0700],
         [-0.3596, -0.9152],
         [ 0.6258,  0.0255],
         [ 0.9545,  0.0643],
         [ 0.3612,  1.1679],
         [-1.3499, -0.5102],
         [ 0.2360, -0.2398],
         [-0.9211,  1.5433]],

        [[ 1.3488, -0.1396],
         [ 0.2858,  0.9651],
         [-2.0371,  0.4931],
         [ 1.4870,  0.5910],
         [ 0.1260, -1.5627],
         [-1.1601, -0.3348],
         [ 0.4478, -0.8016],
         [ 1.5236,  2.5086]],

        [[-0.6631, -0.2513],
         [ 1.0101,  0.1215],
         [ 0.1584,  1.1340],
         [-1.1539, -0.2984],
         [-0.5075, -0.9239],
         [ 0.5467, -1.4948],
         [-1.2057,  0.5718],
         [-0.5974, -0.6937]],

        [[ 1.6455, -0.8030],
         [ 1.3514, -0.2759],
         [-1.5108,  2.1048],
         [ 2.7630, -1.7465],
         [ 1.4516, -1.5103],
         [ 0.8212, -0.2115],
         [ 0.7789,  1.5333],
         [ 1.6097, -0.4032]]])

In [ ]:
torch.manual_seed(42)
a = torch.tril(torch.ones(3, 3))
a = a / torch.sum(a, 1, keepdim=True)
b = torch.randint(0,10,(3,2)).float()
c = a @ b
print('a=')
print(a)
print('--')
print('b=')
print(b)
print('--')
print('c=')
print(c)

a=
tensor([[1.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000],
        [0.3333, 0.3333, 0.3333]])
--
b=
tensor([[2., 7.],
        [6., 4.],
        [6., 5.]])
--
c=
tensor([[2.0000, 7.0000],
        [4.0000, 5.5000],
        [4.6667, 5.3333]])


In [ ]:

torch.manual_seed(1337)
B,T,C = 4,8,2 # batch, time, channels
x = torch.randn(B,T,C)
x.shape

torch.Size([4, 8, 2])

In [ ]:
#simple way of providing context of previous sequence to the current character.by calculating the mean of the prev charactes
xbow = torch.zeros((B,T,C))
for b in range(B):
    for t in range(T):
        xprev = x[b,:t+1] # (t,C)
        xbow[b,t] = torch.mean(xprev, 0)

In [ ]:
#matrix multiplication for the weighted aggregation
wei = torch.tril(torch.ones(T, T))
wei = wei / wei.sum(1, keepdim=True)
xbow2 = wei @ x # (B, T, T) @ (B, T, C) ----> (B, T, C)
torch.allclose(xbow, xbow2)

False

In [ ]:
#  use Softmax
tril = torch.tril(torch.ones(T, T))
wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)
xbow3 = wei @ x
torch.allclose(xbow, xbow3)


False

In [ ]:
# v self-attention!
torch.manual_seed(1337)
B,T,C = 4,8,32
x = torch.randn(B,T,C)

# let's see a single Head perform self-attention
head_size = 16
key = nn.Linear(C, head_size, bias=False)
query = nn.Linear(C, head_size, bias=False)
value = nn.Linear(C, head_size, bias=False)
k = key(x)   # (B, T, 16)
q = query(x) # (B, T, 16)
wei =  q @ k.transpose(-2, -1) # (B, T, 16) @ (B, 16, T) ---> (B, T, T)

tril = torch.tril(torch.ones(T, T))
#wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)

v = value(x)
out = wei @ v
#out = wei @ x

out.shape

torch.Size([4, 8, 16])

In [ ]:
wei[0]

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1574, 0.8426, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2088, 0.1646, 0.6266, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5792, 0.1187, 0.1889, 0.1131, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0294, 0.1052, 0.0469, 0.0276, 0.7909, 0.0000, 0.0000, 0.0000],
        [0.0176, 0.2689, 0.0215, 0.0089, 0.6812, 0.0019, 0.0000, 0.0000],
        [0.1691, 0.4066, 0.0438, 0.0416, 0.1048, 0.2012, 0.0329, 0.0000],
        [0.0210, 0.0843, 0.0555, 0.2297, 0.0573, 0.0709, 0.2423, 0.2391]],
       grad_fn=<SelectBackward0>)

self attention implementation . it just communicates between the previous character and the current one to predict the next one. here we are just using matrix multiplication of v q and k vector .we do linear transformatin on it.

In [ ]:
import torch
import torch.nn as nn
from google.colab import drive
from torch.nn import functional as F

# hyperparameters
batch_size = 16 # how many independent sequences will we process in parallel?
block_size = 32 # what is the maximum context length for predictions?
max_iters = 5000
eval_interval = 100
learning_rate = 1e-3
device = 'cuda' if torch.cuda.is_available() else 'cpu'
eval_iters = 200
n_embd = 64
n_head = 4
n_layer = 4
dropout = 0.0
# ------------

torch.manual_seed(1337)


# Mount Google Drive
drive.mount('/content/drive')
#loading the da6ta from the google drive
train_text_path = '/content/drive/MyDrive/Chat.txt'                        #! where the content folder is located and how is it accessible from here

#opening the file and reading it

with open(train_text_path,'r',encoding='utf-8') as f:
  raw_text = f.read()


# here are all the unique characters that occur in this text
chars = sorted(list(set(text)))
vocab_size = len(chars)
# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

# Train and test splits
data = torch.tensor(encode(text), dtype=torch.long)
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]

# data loading
def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

@torch.no_grad()
def estimate_loss():
    out = {}
    model.eval()
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            X, Y = get_batch(split)
            logits, loss = model(X, Y)
            losses[k] = loss.item()
        out[split] = losses.mean()
    model.train()
    return out

class Head(nn.Module):
    """ one head of self-attention """

    def __init__(self, head_size):
        super().__init__()
        self.key = nn.Linear(n_embd, head_size, bias=False)
        self.query = nn.Linear(n_embd, head_size, bias=False)
        self.value = nn.Linear(n_embd, head_size, bias=False)
        self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size)))

        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        B,T,C = x.shape
        k = self.key(x)   # (B,T,C)
        q = self.query(x) # (B,T,C)
        # compute attention scores ("affinities")
        wei = q @ k.transpose(-2,-1) * C**-0.5 # (B, T, C) @ (B, C, T) -> (B, T, T)
        wei = wei.masked_fill(self.tril[:T, :T] == 0, float('-inf')) # (B, T, T)
        wei = F.softmax(wei, dim=-1) # (B, T, T)
        wei = self.dropout(wei)
        # perform the weighted aggregation of the values
        v = self.value(x) # (B,T,C)
        out = wei @ v # (B, T, T) @ (B, T, C) -> (B, T, C)
        return out

class MultiHeadAttention(nn.Module):
    """ multiple heads of self-attention in parallel """

    def __init__(self, num_heads, head_size):
        super().__init__()
        self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)])
        self.proj = nn.Linear(n_embd, n_embd)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim=-1)
        out = self.dropout(self.proj(out))
        return out

class FeedFoward(nn.Module):
    """ a simple linear layer followed by a non-linearity """

    def __init__(self, n_embd):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd, 4 * n_embd),
            nn.ReLU(),
            nn.Linear(4 * n_embd, n_embd),
            nn.Dropout(dropout),
        )

    def forward(self, x):
        return self.net(x)

class Block(nn.Module):
    """ Transformer block: communication followed by computation """

    def __init__(self, n_embd, n_head):
        # n_embd: embedding dimension, n_head: the number of heads we'd like
        super().__init__()
        head_size = n_embd // n_head
        self.sa = MultiHeadAttention(n_head, head_size)
        self.ffwd = FeedFoward(n_embd)
        self.ln1 = nn.LayerNorm(n_embd)
        self.ln2 = nn.LayerNorm(n_embd)

    def forward(self, x):
        x = x + self.sa(self.ln1(x))
        x = x + self.ffwd(self.ln2(x))
        return x

# super simple bigram model
class BigramLanguageModel(nn.Module):

    def __init__(self):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.position_embedding_table = nn.Embedding(block_size, n_embd)
        self.blocks = nn.Sequential(*[Block(n_embd, n_head=n_head) for _ in range(n_layer)])
        self.ln_f = nn.LayerNorm(n_embd) # final layer norm
        self.lm_head = nn.Linear(n_embd, vocab_size)

    def forward(self, idx, targets=None):
        B, T = idx.shape

        # idx and targets are both (B,T) tensor of integers
        tok_emb = self.token_embedding_table(idx) # (B,T,C)
        pos_emb = self.position_embedding_table(torch.arange(T, device=device)) # (T,C)
        x = tok_emb + pos_emb # (B,T,C)
        x = self.blocks(x) # (B,T,C)
        x = self.ln_f(x) # (B,T,C)
        logits = self.lm_head(x) # (B,T,vocab_size)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # crop idx to the last block_size tokens
            idx_cond = idx[:, -block_size:]
            # get the predictions
            logits, loss = self(idx_cond)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

model = BigramLanguageModel()
m = model.to(device)
# print the number of parameters in the model
print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')

# create a PyTorch optimizer
optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)

for iter in range(max_iters):

    # every once in a while evaluate the loss on train and val sets
    if iter % eval_interval == 0 or iter == max_iters - 1:
        losses = estimate_loss()
        print(f"step {iter}: train loss {losses['train']:.4f}, val loss {losses['val']:.4f}")

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = model(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

# generate from the model
context = torch.zeros((1, 1), dtype=torch.long, device=device)
print(decode(m.generate(context, max_new_tokens=2000)[0].tolist()))

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
0.213341 M parameters
step 0: train loss 4.6488, val loss 4.6532
step 100: train loss 1.8131, val loss 1.9865
step 200: train loss 1.4404, val loss 1.6169
step 300: train loss 1.3178, val loss 1.5509
step 400: train loss 1.2754, val loss 1.4875
step 500: train loss 1.2249, val loss 1.3974
step 600: train loss 1.1907, val loss 1.3489
step 700: train loss 1.1561, val loss 1.3378
step 800: train loss 1.1491, val loss 1.3538
step 900: train loss 1.1091, val loss 1.3443
step 1000: train loss 1.1214, val loss 1.2888
step 1100: train loss 1.0743, val loss 1.2517
step 1200: train loss 1.0585, val loss 1.2901
step 1300: train loss 1.0278, val loss 1.2145
step 1400: train loss 1.0125, val loss 1.2139
step 1500: train loss 1.0191, val loss 1.1903
step 1600: train loss 0.9945, val loss 1.1763
step 1700: train loss 0.9735, val loss 1.1854
step 1800: train loss 0.9837, val

It is an character level decoder only trasformer.predictes the next charcter in this sequence.
It successfully trained mimics the conversation between two individuals.
it implements positional encoding,multihead self attention ,add and norm and feed forward sections in transformer to achive it.

framework:pytorch